version: '3.8'
services:
  postgres:
    image: postgis/postgis:15-3.3 # PostgreSQL version spatiale intégrée !
    environment:
      POSTGRES_USER: nexride
      POSTGRES_PASSWORD: superpassword
      POSTGRES_DB: nexride_db
    ports:
      - "5432:5432"
  
  redis:
    image: redis:7-alpine # Version légère de Redis
    ports:
      - "6379:6379"